### ISSUE TITLE
Which is submitted for MPW7 tape out

### ISSUE THREAD

**Issue by vijayank88** [Nguyen-C-Dao/caravel_rocket_alpha#1]
@Nguyen-C-Dao 
Can you please point me which `user_project_wrapper` submitted for MPW7 shuttle?
Unable to locate https://github.com/Nguyen-C-Dao/caravel_rocket_alpha/blob/main/openlane/user_project_wrapper/config.tcl#L59 lef/gds files.

**Comment by Nguyen-C-Dao** [comment]
Hi @vijayank88, the files (.gds/.lef/.v) were uploaded. Thanks
