### ISSUE TITLE
IR drop report fails

### ISSUE THREAD

**Issue by vijayank88** [Nguyen-C-Dao/caravel_rocket_alpha#2]
Is OpenLane flow completes without any issue at your end?
Due to macro size occupies complete core area, there are unconnected power stripes. Flow fails during IR drop report stage.
```
[STEP 22]
[INFO]: Creating IR Drop Report (log: logs/signoff/22-irdrop.log)...
[ERROR]: during executing openroad script /openlane/scripts/openroad/irdrop.tcl
[ERROR]: Log: designs/rocket_alpha/runs/RUN_2022.12.30_07.20.56/logs/signoff/22-irdrop.log
[ERROR]: Last 10 lines:
[WARNING PSM-0038] Unconnected PDN node on net vccd1 at location (30.520um, 755.640um), layer: 6.
[WARNING PSM-0038] Unconnected PDN node on net vccd1 at location (30.520um, 395.640um), layer: 5.
[WARNING PSM-0038] Unconnected PDN node on net vccd1 at location (30.520um, 395.640um), layer: 6.
[WARNING PSM-0038] Unconnected PDN node on net vccd1 at location (30.520um, 215.640um), layer: 5.
[WARNING PSM-0038] Unconnected PDN node on net vccd1 at location (30.520um, 215.640um), layer: 6.
[WARNING PSM-0038] Unconnected PDN node on net vccd1 at location (30.520um, 35.640um), layer: 5.
[WARNING PSM-0038] Unconnected PDN node on net vccd1 at location (30.520um, 35.640um), layer: 6.
[ERROR PSM-0078] IR drop setup failed.  Analysis can't proceed.
Error: irdrop.tcl, 37 PSM-0078
child process exited abnormally
```

**Comment by Nguyen-C-Dao** [comment]
Hi @vijayank88, I did not set IR Drop check for the top user_project_wrapper. There was no such an IRDrop error. 
The Unconnected power stripes shown above do not affect the entire PDN, there are sufficient power connections at different places/stripes. 
The submodule/macro (user_project_wrapper1) passed the IRDrop check.

**Comment by vijayank88** [comment]
@Nguyen-C-Dao 
`user_project_wrapper` and `user_project_wrapper1`. Which wrapper is submitted for shuttle?
By default i took `user_project_wrapper`. Should I switch to `wrapper1`?

**Comment by Nguyen-C-Dao** [comment]
No, the user_project_wrapper (submitted) is the top module and user_project_wrapper1 is the submodule/macro.

**Comment by vijayank88** [comment]
ok. Thanks. I'll check again.
